### ISSUE TITLE
space is remove

### ISSUE THREAD

**Issue by t-mori-sm** [nhn/tui.editor#1000]
## Describe the bug
space is remove by getHtml().

## Expected behavior
```
setHtml(" aaaaa")
setHtml("&nbsp;aaaaa")
setHtml("　aaaaa")
```
getHtml():
```
<p>aaaaa</p>
```

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser Chrome
 - Version 2.1.2

**Comment by seonim-ryu** [comment]
@t-mori-sm First of all, this is not a bug. To understand this issue, you need to know how Markdown and WYSIWYG work in the editor.

When calling `setHtml()`, the input html is converted to Markdown syntax. Because the Editor manages the data with markdown. And when `getHtml()` is called, the Markdown syntax is converted back to html and output.

At this time, the white space at the beginning of the plain text (`paragraph`) is ignored according to the CommonMark specification. So it is correct that the Markdown syntax is displayed as html as follows, with the leading whitespace disappeared.

> https://spec.commonmark.org/dingus/

* When the Markdown syntax is rendered
![md-preview](https://user-images.githubusercontent.com/18183560/82625843-28c3dd00-9c21-11ea-989a-ce19ed5d24b9.png)

* When Markdown syntax is converted to html
![html](https://user-images.githubusercontent.com/18183560/82625849-2d889100-9c21-11ea-8b4d-236ef3d42eca.png)
