### ISSUE TITLE
Hot to remove <br> tags when inserting additional break points.

### ISSUE THREAD

**Issue by peymanforceman** [nhn/tui.editor#1049]
Hi Guys when I'm in WYSIWYG mode and enter a few lines after changing it to Markdown mode , I see a few <br> tags in the Markdown mode which is ruining the whole Markdown mode , because it should be Markdown and we can't include html tags with Markdown codes.

```
asd

<br>
<br>
asd
```

do you have any solution for it ?

how can I avoid it ? 

If you have any suggestions , please share it with me. I wanted to write a function which removes all these tags but the problem with that method is that it also removes <br> tags from code blocks if there was any and I think it's not a good idea to use it this way because users may use <br> tags in the code blocks

Regards

**Comment by seonim-ryu** [comment]
@peymanforceman In the markdown specification, even if multiple newlines are entered, it is recognized as one line. So, in order to keep empty newlines entered in Wizwick in markdown as intended by the user, `<br>` must be added. There is currently no way to remove this `<br>`.

I have one question, because I don't understand what you said last. Could you explain it in more detail?

> If you have any suggestions , please share it with me. I wanted to write a function which removes all these tags but the problem with that method is that it also removes
tags from code blocks if there was any and I think it's not a good idea to use it this way because users may use tags in the code blocks

**Comment by peymanforceman** [comment]
@seonim-ryu  : thanks for your response. I think there is solution , because new lines can be like `\n` in Markdown section. 

Actually we used  this editor for one of our projects which is something similar to stackoverflow.

the editor works great , but this `<br />` tags should not be a part of markdown codes because markdown codes are different with html codes. 

so as a solution I wanted to make a js function to remove these `<br />` tags or change them to `\n` 

but the problem with that is that if I implement this function as a temporary solution for removing <br /> tags from Markdown section , it also removes `<br />` tags in the code blocks too which it should not be like that. I want to remove or replace `<br />` tags just out of code blocks.

**Comment by davidfregoli** [comment]
Hey, @peymanforceman, have you found an elegant solution for this? I agree that the current implementation is indeed suboptimal
