### ISSUE TITLE
How do I insert Markdown in WYSIWYG mode?

### ISSUE THREAD

**Issue by davidames** [nhn/tui.editor#1056]
## Summary
When in Markdown mode, if you pass a mark-down string to insertText, it inserts as markdown.  However, when it WYSIWYG model.  InsertText will not set the markdown.  

## Example:
In Markdown Mode:  insertText('this is a string with * * bold * * in it') and then swapping to WYSIWIG mode
![image](https://user-images.githubusercontent.com/1831867/85211196-25d81b80-b38a-11ea-8f9e-8daf8589d154.png)

In  WYSIWIG mode calling insertText('this is a string with * * bold * * in it')
![image](https://user-images.githubusercontent.com/1831867/85211189-0e009780-b38a-11ea-8bd3-0b2950c84b8a.png)

## Version
Version 2.2

## Additional context
I would like a way to insert markdown "snippets" when in WYSIWIG mode and have them display correctly.

**Comment by seonim-ryu** [comment]
@davidames Currently `insertText` is a function that adds the input character as it is, so it works. I think it can be done using commands instead of `insertText` api. Would you like to check it out?

> https://nhn.github.io/tui.editor/latest/tutorial-example18-using-command

**Comment by JensUweB** [comment]
> @davidames Currently `insertText` is a function that adds the input character as it is, so it works. I think it can be done using commands instead of `insertText` api. Would you like to check it out?
> 
> > https://nhn.github.io/tui.editor/latest/tutorial-example18-using-command

This works, if you just want to use default markdown commands. But you cannot create your own commands, so that you are stuck with the default ones.
My team uses a custom youtube embed plugin. We use the codeblock for that like the one in the [documentation](https://nhn.github.io/tui.editor/latest/tutorial-example17-creating-plugin). We have implemented a custom button, to insert the youtube embed codeblock with `editor.insertText(" ``` youtube YOUTUBE-ID ```" ) `

This works fine in markdown mode, but it does not work at all in wysiwyg mode of course. We could use `editor.setMarkdown(...)` in wysiwyg mode, but that just overrides the markdown content.

Another idea was to insert a custom uid with `editor.insertText(...)`, read the markdown content with `editor.getMarkdown( )`, search & replace your uid and set markdown `editor.setMarkdown(...)`

Any suggestions for a better way?
