### ISSUE TITLE
Can't I use v-model?

### ISSUE THREAD

**Issue by mygyugyu** [nhn/tui.editor#1067]
## Summary
I installed '@toast-ui/vue-editor' to use the editor in vue. The component was imported and  registered.
I am trying to use it like this in templete

```
<editor
      :options="editorOptions"
      v-model="createParams.content"
      height="300px"
     initialEditType="wysiwyg"   />
```

but data binding doesn't work.

https://github.com/nhn/tui.editor/issues/1023

Is the v-model still not working?

## Version
 "@toast-ui/vue-editor": "^2.2.0"

**Comment by derek-knox** [comment]
@mygyugyu This is one way in case you missed it https://github.com/nhn/tui.editor/issues/1023#issuecomment-643024296.

Basically Toast UI manages a more complicated internal state (hence the comment about perf concerns). For now our solution is:
1. Set an `:initial-value` (you need this instead of `v-model` until implemented)
    - https://gitlab.com/gitlab-org/gitlab/-/blob/master/app/assets/javascripts/vue_shared/components/rich_content_editor/rich_content_editor.vue#L123
2. Expose an API to update this value
    - https://gitlab.com/gitlab-org/gitlab/-/blob/master/app/assets/javascripts/vue_shared/components/rich_content_editor/rich_content_editor.vue#L81
3. Update the value using the Toast UI ref API `invoke('setMarkdown', newVal);`
    - https://gitlab.com/gitlab-org/gitlab/-/blob/master/app/assets/javascripts/vue_shared/components/rich_content_editor/rich_content_editor.vue#L82

**Comment by justirva09** [comment]
Here's My Sandbox link for onChange  and get value for HTML and MARKDOWN tui/editor with VueJs.

https://codesandbox.io/s/onchange-tuieditor-v4ngb

**Comment by CodyBontecou** [comment]
The links posted by @derek-knox no longer work.

> Here's My Sandbox link for onChange and get value for HTML and MARKDOWN tui/editor with VueJs.
> 
> https://codesandbox.io/s/onchange-tuieditor-v4ngb

This post works though!
