### ISSUE TITLE
Can the available heading options be modified?

### ISSUE THREAD

**Issue by J5Dev** [nhn/tui.editor#1139]
## Summary
Is it possible to edit or customise the options available within the 'heading' dropdown.

Specifically, I want to remove the ability for the user to set the content to be a Heading1, so that the dropdown only features heading options 2-6.

I can see ways to create custom buttons, including creating a custom heading button. Although, this requires firing the event 'openHeadingSelect', which will simply return the default heading options.

What I wanting is to customise what options appear when calling openHeadingSelect.

Is this possible?

## Version
Version: V2.3.1
Wrapper/App: Vue (If relevant)

**Comment by seonim-ryu** [comment]
@J5Dev Sorry for the late answer. First of all, the feature you mentioned is not provided, and I think I need to consider some considerations for this feature. Even if you remove the dropdown menu of `h1` from the toolbar, the header element is preserved because the `# h1` syntax is still available in Markdown. So, in my opinion, simply using the `openHeadingSelect` event will not solve this problem. I need to find a way to customize this to the user in a different way. I'll review it and let you know.
