### ISSUE TITLE
npm found vulnerability in package

### ISSUE THREAD

**Issue by gincheong** [nhn/tui.editor#1148]
## Summary
when install editor with npm, npm report security vulnerability.
But [TOAST UI Monthly 2020.06](https://ui.toast.com/weekly-pick/ko_monthly_202006/) says XSS vulnerability fixed in version 2.2.0.
Should I just ignore this report?

## Screenshots
![image](https://user-images.githubusercontent.com/24225401/90460585-1fbeab00-e13f-11ea-9da6-7e1fb697a5c2.png)

## Version
2.3.1

**Comment by seonim-ryu** [comment]
@gincheong When I checked the issue you registered, it seems to be due to the issue registered in npmjs below.

> http://npmjs.com/advisories/1521

First, explaining this situation, there was a report from npmjs about XSS vulnerability. So, the Editor first added the `customHTMLSanitaizer` option in version 2.1.0 (let the user handle sanitizing manually). Later, in version 2.2.0, the default sanitizer function of the Editor was improved to remove the element that caused XSS.

I think the reason npmjs registered the warning message is because it was applied in version 2.1.0. For now, you can ignore that message. But I think we should ask npmjs to fix the warning message.

Thanks for reporting the issue!
