### ISSUE TITLE
Using vue template in custom plugin

### ISSUE THREAD

**Issue by lucianobosco** [nhn/tui.editor#1203]
Hi! I'm thinking to move from vue CKeditor to Toast UI Editor, but I need to be sure that custom plugins can be developed by using Vue js template.
Basically, I need to create a custom button that when it's clicked a bootstrap vue modal is opened. The purpose of this button/modal is to search uploaded media from server or upload a new file and insert it in content.
I've taken a look at the documentation and everything seems to point that plugins can be created just by js.
Any guidance will be appreciated.

**Comment by seonim-ryu** [comment]
@lucianobosco What I understand is that there is logic to create button/modal within a custom plugin, and I think you asked if you can use Vue template at this time. First of all, there is currently no way to use Vue template in the Editor. And whether or not to support templates is difficult because of the internal structure. If the Editor supports it, it will be possible after the next major version update. (Support is difficult in v2)
