### ISSUE TITLE
The Ordered list show bug

### ISSUE THREAD

**Issue by Rain120** [nhn/tui.editor#1221]
## Steps

Always choose the ordered list, view more 👉👉👉  [Here](https://ui.toast.com/tui-editor/)

![image](https://user-images.githubusercontent.com/20939839/95536642-0be84480-0a1e-11eb-855e-27251d2d4ab9.png)

**Comment by seonim-ryu** [comment]
@Rain120 This is not a bug, it's the [CommonMark's spec](https://spec.commonmark.org/0.29/#ordered-list-marker). When creating an AST with markdown syntax, if the list marker follows a rule such as `1.`, an ordered list is created. List items created later are created as list item nodes of the same type until the next list appears. So, even when rendered in the right preview area, it is not displayed based on syntax, but the current behavior is correct because nodes created with AST are rendered with ʻol` element

![common-mark](https://user-images.githubusercontent.com/18183560/95866357-cb345680-0da2-11eb-9b59-9b85d3bbe731.png)

**Comment by Rain120** [comment]
@seonim-ryu
