### ISSUE TITLE
Text styling inside code block?

### ISSUE THREAD

**Issue by srcdes** [nhn/tui.editor#1235]
## Version
2.4.0

## Development Environment
chrome 86.0.4240.80(x86_64), macOS 10.15.7

## Current Behavior & Expected Behavior
Text styling doesn't work inside code block. The first line is expected behavior and second one is actual behavior.

![image](https://user-images.githubusercontent.com/32840866/96661610-7044c580-1387-11eb-9719-0a86b2dc48c0.png)

**Comment by seonim-ryu** [comment]
@srcdes The text entered in the code block must not be applied with the markdown emphasis syntax. Since they correspond to the code, it is correct that they are displayed as entered. For code highlighting, it's right to use this [plugin](https://github.com/nhn/tui.editor/tree/master/plugins/code-syntax-highlight) to handle it.

> CommonMark Spec : https://spec.commonmark.org/0.29/#fenced-code-blocks
