### ISSUE TITLE
Chart, image, uml diagram styling.

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#1237]
![Screenshot (423)](https://user-images.githubusercontent.com/54087826/96712457-e9293900-13ea-11eb-9614-6aad5bdb1c0a.png)
# 1
You can see in this UML diagram, UML is left aligned. 
I want it to be centered aligned. This is happening with images and charts also.
How can i do that?
# 2
This diagram has a background color like _**gray**_. How can I remove it?

**Comment by seonim-ryu** [comment]
@ats1999 In the first question, I think you can find the `pre` tag and modify the style yourself so that it is centered.

Second, the UML plugin uses [plantuml-encoder](https://www.npmjs.com/package/plantuml-encoder), but it seems to be a problem with the image used in `plantuml-encoder`. Would you like to contact `plantuml-encoder`?

**Comment by ats1999** [comment]
thanks
