### ISSUE TITLE
How to add a link button to the left of heading. 

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#1278]
As GitHub adds a link button to the left of the heading. This is useful.

https://codesandbox.io/s/holy-paper-p384e?file=/src/App.js
see it live

for better visual type below **MD** into the editor. 
```
# 1
# 2
# 3
# 4 
# 5 
# 6
# 7
# 8 
# 9
# 10
# 11 
# 12
# 13
# 14
# 15
# 16
 # 18
 # 19
 # 20
```

This helps us to share a page section. 

# is there any better way of doing this.

**Comment by seonim-ryu** [comment]
@ats1999 The code sandbox example you made was interesting. First of all, there is no way to solve that in Markdown in the current version. I think you can use the method of using image syntax in the heading.
```md
# [![image](imgLink)](link) heading
```
Otherwise, I think you will have to provide **custom syntax** or plugins. The custom syntax function is being developed in version 3.0.

**Comment by seonim-ryu** [comment]
@ats1999 And looking at the code, you are creating and adding the tag `a` with `handleChange`, but I recommend using the [`customHTMLRenderer`](https://github.com/nhn/tui.editor/blob/master/apps/editor/docs/custom-html-renderer.md) option.
