### ISSUE TITLE
Editing in preview mode 

### ISSUE THREAD

**Issue by mikeerickson** [nhn/tui.editor#1420]
Hello,

we have a requirement to allow editing of markdown files in preview mode.  The existing functionality supports our POC requirements, but we do need to supporting editing in preview (aka WYSIWYG) mode.

**Comment by seonim-ryu** [comment]
@mikeerickson I think the feature you're talking about is allowing you to enter and edit Markdown syntax in WYSIWYG. For example, typing `# ` will convert it to `<h1></h1>` in the WYSIWYG editor. First of all, it does not support a feature because it does not match the current Editor's concept. The usability and UI are completely different from the Editor. This feature has a lot to consider, and we'll review it later.

**Comment by mikeerickson** [comment]
Yes, you are correct, that is what I am looking for.  Thanks for your input, I will continue my quest.
