### ISSUE TITLE
"TypeError: __webpack_modules__[moduleId] is not a function" in React

### ISSUE THREAD

**Issue by partoneplay** [nhn/tui.editor#1586]
## Describe the bug
When I add some plugins, such as `uml` `chart`
```jsx
import chart from "@toast-ui/editor-plugin-chart";
```
then the error below
```
TypeError: __webpack_modules__[moduleId] is not a function
```

## To Reproduce
Just import the plugin in a React component

## Screenshots
<img width="996" alt="截屏2021-06-18 11 32 19" src="https://user-images.githubusercontent.com/5189132/122502253-da9e2a80-d028-11eb-9fe0-555688e40ba1.png">

**Comment by js87zz** [comment]
@partoneplay 
Can you give us your webpack version and the code snippet of webpack configuration?

**Comment by js87zz** [comment]
@partoneplay 
I think this issue is same as [it](https://github.com/nhn/tui.editor/issues/1589). I will check it . Thanks!

**Comment by ats1999** [comment]
> @partoneplay
> Can you give us your webpack version and the code snippet of webpack configuration?

it's CRA and latest React

**Comment by js87zz** [comment]
@partoneplay 
It was a compatibility issue between version 4 and version 5 of the webpack to handle external modules.  I can resolve the issue by changing the bundle format(`cjs` => `umd`).

I was able to fix it quickly because it was easily reproduced in your project. Thank you :)

* released plugins
  * `@toast-ui/editor-plugin-uml@3.0.1`
  * `@toast-ui/editor-plugin-chart@3.0.1`
  * `@toast-ui/editor-plugin-color-syntax@3.0.1`

**Comment by ats1999** [comment]
Glad to here that reproduced code was helpful
