### ISSUE TITLE
i18n language is not working in NextJS in @toast-ui/editor 3.0.2

### ISSUE THREAD

**Issue by Yangseungchan** [nhn/tui.editor#1737]
## Describe the bug
I'm still having the problem in applying KR language at editor which is different from importing i18n  in the [this issue](https://github.com/nhn/tui.editor/issues/1677). Hopefully, I saw the new release which fixes the importing i18n bug and try to apply new version to set KR language. However, even though I updated the new version, it still triggers an error described in the below screenshot.  **What I did is to set the language prop of Editor component as 'ko' in nextJS app** .  You can check the code through [this link](https://codesandbox.io/s/dazzling-microservice-lyp36?file=/components/Editor/Editor.js). 

## To Reproduce

1. Setting language prop as 'ko' of Editor component(You can check it at **/components/Editor/Editor.js** in the above code link)

2. dynmaic importing the editor component(As it doesn't support ssr)  and redering the editor at the page. (You can check it at **/pages/index.js** in the above code link

## Screenshots

![problem](https://user-images.githubusercontent.com/38908080/128315932-daf71259-0341-4d69-8908-e6f3f7bb7ff9.png)

## Desktop (please complete the following information):
 - OS: MacOS
 - Browser: Chrome
 - Versions: 
1.  @toast-ui/react-editor : 3.0.2
2. NextJS : 11.0.1
3. react : 17.0.2

## Additional context
Thanks in advance for caring the issues :)

**Comment by js87zz** [comment]
@Yangseungchan 
I checked this out and it was a really complicated problem.

It was caused by the difference between the `@toast-ui/react-editor` and the main editor(`@toast-ui/editor`) refer to `i18n` module in different bundles in next.js(`@toast-ui/react-editor` refers to `i18n` in **UMD** bundle file and `@toast-ui/editor` refers to `i18n` in **esm** bundle file).
I'm not sure, but I think there's a problem with the next.js webpack environment. 

Anyway, to solve this problem clearly, I added esm bundle to React wrapper to refer to the same bundle result. It'll be fixed and released on this week. Thank you!

**Comment by Yangseungchan** [comment]
Thanks for caring the issue. I saw the recent commit to fix this issue. But there seems to be no version update on the @toast-ui/react-editor. Is this new change applied automatically without any updates?

**Comment by js87zz** [comment]
@Yangseungchan 
No, it's not released yet. 
The editor will be released today or tommorow.

**Comment by js87zz** [comment]
@Yangseungchan 
The bug has been fixed in `v3.0.3`.

**Comment by Yangseungchan** [comment]
Really appreciate it!

**Comment by Yangseungchan** [comment]
Really appreciate it!
