### ISSUE TITLE
GDPR issues with by-default GA integration?

### ISSUE THREAD

**Issue by Powersource** [nhn/tui.editor#1820]
If you go to the react component [docs here](https://github.com/nhn/tui.editor/tree/master/apps/react-editor#collect-statistics-on-the-use-of-open-source) you can read

> React Wrapper of TOAST UI Editor applies Google Analytics (GA) to collect statistics on the use of open source, in order to identify how widely TOAST UI Editor is used throughout the world. It also serves as important index to determine the future course of projects. location.hostname (e.g. ui.toast.com) is to be collected and the sole purpose is nothing but to measure statistics on the usage. To disable GA, use the usageStatistics props like the example below.
>
> ```jsx
><Editor
>  ...
>  usageStatistics={false}
>/>
>```

but my understanding of gdpr is that the user has to opt into this kind of tracking.

So my suggestion is to change this prop to be `false` by default. I can send a PR if that'd be useful.

**Comment by calumk** [comment]
I think It would be up to you as the website 'owner' to ensure this is correctly implemented - the tui.editor  is free to do whatever it wants, if you use it, then you are responsible for checking/disabling/notifying user of this.

GDPR is a EU only thing.

**Comment by js87zz** [comment]
@Powersource 
Sorry for late replying.

We provide our open sources through the Github. At this time, we collect the domain addresses of users who use our open source.

Reviewing the above base facts, IP addresses collected through our open sources correspond to personal information as online identifiers for people in GDPR, but It is difficult to say that open source provides services to EU residents, so it is unlikely to be subject to GDPR compliance (we operate web pages in English and access to countries around the world due to the nature of the Internet). In addition, the current proportion of EU users is about 10%, but if the proportion increases extremely in the future, it will be reviewed.

Internally, it was consulted with the legal team, and it is judged that there is no issue with the GDPR.

**Comment by capital-G** [comment]
I find this definitely a very problematic default.

If it is [not even allowed use google fonts w/o consent in GDPR countries](https://meetanshi.com/blog/google-fonts-gdpr-compliant/) so I highly doubt that adding their tracker is.
This can lead to financial risk to many users within the EU - of course in the end everyone has to verify/keep track of what one deploys but I find that this kind of tracking of users and usage is something that open source does not stand for.

**I strongly vouch to make this option an opt-in!**

At least make transparent what you do with the collected data - make public reports.
