### ISSUE TITLE
Widget rendered not correct in markdown mode

### ISSUE THREAD

**Issue by cary-hu** [nhn/tui.editor#1899]
## Describe the bug
In Markdown mode, Input keyword for widget rule, and the widget rendered correctly but the preview panel rendered not correctly

## To Reproduce
![Animation2](https://user-images.githubusercontent.com/41052104/136917157-05926050-0e1b-4c96-a06e-1671d2016007.gif)

## Desktop (please complete the following information):
 - OS: Windows 11
 - Browser: chrome
 - Version: latest
 - TuiEditor: 3.1.0

**Comment by js87zz** [comment]
@cary-hu 
Since it's an issue related to widget rules, I'd appreciate it if you could give me the setting code for the widget.

**Comment by cary-hu** [comment]
oh... sorry for that, 
```typescript
widgetRules: [
  {
    rule: /%code-tab-block%/,
    toDOM(text) {
      const rule = /%code-tab-block%/;
      const matched = text.match(rule);
      const a = <div>test</div>

      return a;
    },
  },
],
```

More info: I have use https://github.com/Lusito/tsx-dom to provide HTMLElement for widget

**Comment by js87zz** [comment]
@js87zz 
I checked issue. 
I'll dig deep the cause and solution and write the comment here. Thank you!

**Comment by js87zz** [comment]
@cary-hu 
I looked at this issue again in detail. 
Our widget node is adding only inline nodes wrapped in `span` tag. Therefore, block nodes such as `div` cannot be properly rendered in widget node due to the DOM structure.

There is no support plan for the widget for block nodes yet, so it is recommended to create and use inline widget node. Thank you for the issue report and sorry for the late response to the cause 😭

**Comment by cary-hu** [comment]
Ok got that. thanks for your reply.
