### ISSUE TITLE
Error in mounted hook: "TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by bilguun87** [nhn/tui.editor#2100]
Hi dears
First of all sorry for my bad English. I trying to set options. But when I try to set options, it gives me below error.
**Error in mounted hook: "TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.**

**Comment by js87zz** [comment]
@bilguun87 
Please explain the issue clearly according to our issue template. 
There's nothing that can be solved with your information now.

**Comment by mmorainville** [comment]
Hi,

Just for additional info, I have the exact same problem after upgrading from https://www.npmjs.com/package/@toast-ui/vue-editor from 3.1.1 to 2.5.4 (yes, according to npm it's an upgrade...).

If I comment out the toolbarItems, it works correctly, so I'm guessing the problem comes from there.
It doesn't matter what I have set in the option, as long as I have a toolbarItems property it crashes.

```
        toolbarItems: [
          ['heading', 'bold', 'italic', 'strike'],
          ['hr', 'quote'],
          ['ul', 'ol', 'task'],
          ['table', 'image', 'link'],
          ['code', 'codeblock'],
        ],
```

**Comment by rytmis** [comment]
The example seems to be outdated. Typings for toolbar items suggest that it's an array of strings, not an array of arrays. For example, this works:

```javascript
    toolbarItems: [
        'heading', 
        'bold',
        'italic',
        'strike',
        'divider',
        'hr',
        'quote'
    ]
```
