### ISSUE TITLE
how to apply addImageBlobHook in Vue.js??

### ISSUE THREAD

**Issue by rkddbs1031** [nhn/tui.editor#2199]
## Summary
Hello. I'm trying to apply addImageBlobHook, a function that fires when an image is uploaded.
When uploading an image to the editor, I am trying to output the editor by receiving the url of the photo as a return value as a return value as a callback function without saving base64-encoded data.
I searched for a way to remove the default function using removeHook and set it again, but I have no idea how to apply it. Any help would be appreciated..

## Screenshots
`<editor
    :options="editorOptions"
    minHeight="400px"
    initialEditType="wysiwyg"
    ref="toastuiEditor"
  />`

`import '@toast-ui/editor/dist/toastui-editor.css';
import 'tui-color-picker/dist/tui-color-picker.css';
import '@toast-ui/editor-plugin-color-syntax/dist/toastui-editor-plugin-color-syntax.css';

import colorSyntax from '@toast-ui/editor-plugin-color-syntax';
import { Editor } from '@toast-ui/vue-editor';`

It was imported as above, and the data is written as follows.

<img width="413" alt="image" src="https://user-images.githubusercontent.com/65527334/149474681-a01205cb-20cc-44e8-ac0f-bfa2f378a54e.png">

When declaring the callback function, when I tried to call a method using this, an error appears in the console window as well.
Is it not using this syntax.. or how to apply the code below in Vue.js..

<img width="381" alt="image" src="https://user-images.githubusercontent.com/65527334/149473962-e4b74f80-c1e3-4843-9ee0-bfc9fb4e3668.png">

## Version
    "@toast-ui/editor": "^3.1.2",
    "@toast-ui/vue-editor": "^3.1.2",

**Comment by js87zz** [comment]
@rkddbs1031 
It works normally when done as below. Can you check to pass props `options`?
If it doesn't work, please upload your code in code sandbox to resolve the issue.
```js
new Vue({
  data() {
    return {
      initialValue: content,
      options: {
        hooks: {
          addImageBlobHook(blob, callback) {
            // do something
            callback('image url', 'alt text');
          },
        },
      },
    };
  },
  template: '<editor height="400px" :options="options" />',
}).$mount('#editor');
```

**Comment by ZeroBean** [comment]
here is my solution:

1. instead of using the @toast-ui/vue-editor, i use the @toast-ui/editor, because it provide the consturtor function

HTML:
![image](https://user-images.githubusercontent.com/33920858/163330232-d187a6a1-33ff-4566-84d5-cd70463315de.png)

Script:

![image](https://user-images.githubusercontent.com/33920858/163330320-d9a1c27a-7fc9-4583-a6b9-f58d00634225.png)


then you could create an initEditor  funtion and use it in the mount life cycle
![image](https://user-images.githubusercontent.com/33920858/163330475-70a85918-c6fa-474c-9296-9f0ce0cd2972.png)
![image](https://user-images.githubusercontent.com/33920858/163330517-6ad8de77-df32-433a-bd24-ff795bb073d5.png)


holpfully can help you!
