### ISSUE TITLE
How to deal with global CSS import when used inside a lib in a Next.JS app

### ISSUE THREAD

**Issue by slax57** [nhn/tui.editor#2732]
## Summary
We currently maintain a React framework called [react-admin](https://github.com/marmelab/react-admin), and we used `@toast-ui/react-editor` to build one of our components.

In this component we imported the `toastui-editor.css` file following the usage instructions in [the package readme](https://www.npmjs.com/package/@toast-ui/react-editor):
```ts
import '@toast-ui/editor/dist/toastui-editor.css';
```

This works fine when used in an app created with `create-react-app` for example, but when using it in a Next.JS app we get the following error:

```
/node_modules/@toast-ui/editor/dist/toastui-editor.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/@react-admin/ra-markdown/esm/src/MarkdownField.js
```

Which leads us to ask the question: what it the appropriate way to deal with this CSS import in our lib?
Are we doing it right and it's only a Next.JS config missing?
Or should we remove the import from our code and ask the users of our lib to import it globally in their code?
Or none of the above?

Thanks

## Version
`"@toast-ui/react-editor": "^3.1.5"`

**Comment by jwlee1108** [comment]
@slax57 

Thank you for the issue. I'm glad you used our project.
I'm sorry, but we're not considering the Next.js environment yet. For now, I think it would be better to have the end user apply globally CSS. 

Recently, the Next.js environmental issue has been opened, and we are going to check it, but there is no exact plan and milestone. Because We have to do various tasks besides TOAST UI. I'm sorry.
