### ISSUE TITLE
Multiple lines table support

### ISSUE THREAD

**Issue by rickywu** [nhn/tui.editor#305]
I use pandoc convert docx to markdown and use multiple line tables
But tui.editor seems don't support this feature 

## Pandoc output
```
+--------------+----------------------+
| **A**        | **B**                |
+==============+======================+
| 1            | multiple line tables |
|              | multiple line tables |
+--------------+----------------------+


```
## Manually formatted for tui.editor

```
|--------------|----------------------|
| **A**        | **B**                |
|--------------|----------------------|
| 1            | multiple line tables |
|              | multiple line tables |
|--------------|----------------------|
```

tui.editor shows

![multi](https://user-images.githubusercontent.com/442398/46243392-59308500-c406-11e8-9682-1e73967bf9bc.png)

Can you support pandoc's output?

**Comment by rickywu** [comment]
Any update or anything I can help for this? thanks!

**Comment by rickywu** [comment]
I found that all multiline tables copy to Excel and then copy to WYSIWYG mode, it works well

I think about use python to extract table in docx and convert to Excel format after that implement paste function then no need tui.editor support pandoc multi line table, any adivce or you can tell me how implement paste function.

**Comment by sohee-lee7** [comment]
If you make a multiline table in Wysiwyg like it, the line breaks are changed to `<br>` when change to Markdown.
![image](https://user-images.githubusercontent.com/42666492/55121814-9ec4d500-513f-11e9-87c6-d1490e47a0ea.png) -> ![image](https://user-images.githubusercontent.com/42666492/55121839-c156ee00-513f-11e9-8619-f93e8a783dd9.png)

If you make a line break in table of Markdown, you should use `<br>`.

Pandoc's ouput is not standard in GFM(https://github.github.com/gfm/) so bellow table is not rendered properly. 
|--------------|----------------------|
| **A**        | **B**                |
|--------------|----------------------|
| 1            | multiple line tables |
|              | multiple line tables |
|--------------|----------------------|

We follow GFM so your suggestion about support multiline in table need to discussion with our team.
And paste logic in Wysiwyg use html tag of clipboard data. That's why multiline table is pasted in the Wysiwyg.

**Comment by rickywu** [comment]
I found pandoc gfm.docx -f docx -t gfm support gfm with limited extensions and multiline table works well in tui editor but except multi line table header

This is pandoc gfm format output table header
```
<table>
<thead>
<tr class="header">
<th>交易卡类</th>
<th>发卡与收单</th>
<th>商户净计金额入账方式</th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td>当日逐笔实时</td>
<td>次日对账后批量</td>
<td>手动入账</td>
</tr>
...
```

tui editor render as:
![image](https://user-images.githubusercontent.com/442398/55127779-37615200-514c-11e9-91ac-5cb49d05dee9.png)

word render as:
![image](https://user-images.githubusercontent.com/442398/55127804-4cd67c00-514c-11e9-98df-d8c575f901e2.png)

If this problem solved then could be perfect, thanks.

**Comment by rickywu** [comment]
Is that possible to support pandoc output?

**Comment by rickywu** [comment]
@seonim-ryu Any update for this issue?

**Comment by rickywu** [comment]
Pandoc not support column span, so close it
