### ISSUE TITLE
How to disable converting html to markdown

### ISSUE THREAD

**Issue by LIFOsitory** [nhn/tui.editor#483]
## Version

1.3.3
## Test Environment

Whale Browser
## Current Behavior
 

마크다운 탭에서 태그를 입력하고 위지윅 탭으로 간 뒤 다시 마크다운 탭으로 돌아오면 태그가 사라집니다.

After I put a tag on the markdown tab and go WYSIWYG tab and return to markdown tab, the tag is gone. 

## Expected Behavior

Html로 입력하면 마크다운으로 바뀌는 기능을 끄고 싶습니다.
제공하는 API 가 있거나 알고 계신 방법이 있으신가요?

I want to turn off the converter which converts HTML to markdown.
Is there any APIs or solutions?

**Comment by sohee-lee7** [comment]
There is no way to turn off that is to change html to markdown because that is our feature.
If you want to maintain html in markdown while change mode, you could use `data-tomark-pass` attribute. But there is one problem that is `data-tomark-pass` works only once. (#366 ) This issue will be fixed in the next release. Please use `data-tomark-pass` to maintain html with the next release.

**Comment by sohee-lee7** [comment]
@LIFOsitory Sorry for late reply. There is no way to maintain html that insert to markdown.
Currently I implement for maintaining html and it will be released next release.
