### ISSUE TITLE
emphasis syntax broken with <span>

### ISSUE THREAD

**Issue by sohee-lee7** [nhn/tui.editor#557]
## Version
v1.4.3

## Test Environment
Chrome

## Current Behavior

![Screen Recording 2019-06-26 at 4 57 42 PM mov](https://user-images.githubusercontent.com/42666492/60162068-b80b1980-9833-11e9-9075-59ff5df94130.gif)

1. Type text in wysiwyg.
2. Select a part of text.
3. Execute bold, italic or strike.
4. Execute color.
5. Convert to markdown

Rendering result of markdown is broken.

![image](https://user-images.githubusercontent.com/42666492/60162130-dec95000-9833-11e9-95b4-b08785f9e5c5.png)

## Expected Behavior

Markdown rendering result should be not broken like this.

![image](https://user-images.githubusercontent.com/42666492/60162157-ea1c7b80-9833-11e9-85ef-fa18c86b908c.png)

**Comment by dongwoo-kim** [comment]
I think this issue is related with limitation of common-mark spec. 
I made an issue for this : https://github.com/commonmark/commonmark-spec/issues/611

According to the common-mark spec, following HTML 
```markdown
a**<span>foo</span>**
```
converts to : 
```html
<p>a**<span>foo</span>**</p>
```
because of preceding `a` and following `<` of opening `**`.

Easy solutions could be inserting non-width whitespace or HTML comments before `**` like below. 

```markdown
a&#8203;**<span>foo</span>**
a<!-- -->**<span>foo</span>**
```

But these solutions looks little bit unnatural, and the users might think of this as an unexpected behavior. I think the most natural way to solve this is using raw HTML (`<b>`) for representing strong emphasis instead of markdown syntax (`**`). 

```markdown
a<b><span>foo</span></b>
```
