### ISSUE TITLE
The creation screen in the toast-editor is different from the print screen in the preview and toast-viewer.(For example, when you hit the enter key)

### ISSUE THREAD

**Issue by saeromCho** [nhn/tui.editor#621]
![스크린샷 2019-09-05 오후 7 08 00](https://user-images.githubusercontent.com/28703206/64333151-ef0a6200-d010-11e9-881a-e9ec24b8c909.png)

Hello!
As you can see in the picture that I captured above, the screen of the preview and viewer is different from the screen of the editor.
Even though you have played enter keys more than five times in the editor's writing, the result is that you hit them once in the preview or in the viewer
When using Toast Editor, I often feel uncomfortable with this issue, so I'd like to ask if you have any ideas for improvement in this area.
Apart from this question, I would like to do direct customization of the source on the issue. I'd like to ask you which part of the code you can modify. For example, I would appreciate it if you let me know the class or variable in the source. Will it be possible?

Thank you for reading it :)
I'll be waiting for your reply.

**Comment by seonim-ryu** [comment]
@saeromCho 
First, let me explain the Markdown editor of `tui-editor`. Currently the Markdown editor follows the [Common Mark's specification](https://spec.commonmark.org). Since the specification ignores more than two newline by hitting enter, the behavior is correct in the markdown preview and the viewer. This works the same in other markdown editors, for example [markdown-it](https://markdown-it.github.io/) or github.

If you want to make a newline explicitly, you can enter `<br>` tag in the Markdown Editor.
```
foo
<br>
<br>
<br>
baz
```
![example](https://user-images.githubusercontent.com/18183560/64343499-97c3bc00-d027-11e9-95d7-8e542207581b.png)

Because this is a specification, there's no way to customize it. 🥺

Thank you for using `tui-editor` and if you have any further questions, please comment!

**Comment by seonim-ryu** [comment]
There are no comments anymore so I'll close this issue.
