### ISSUE TITLE
[feature request] Pasted image has long base64-url makes hard to read or write.

### ISSUE THREAD

**Issue by mu-yu** [nhn/tui.editor#668]
## Version
any version.

## Current Behavior
pasted image is converted to base64 string like `![img](base64href)`, but the base64 string is toooooooooo loooooooooong to read / write other contents.

I think the image should converted like this:
```diff
- ![img](base64href)
+ ![img][imgTag]
// other md content.

// at the bottom of the file
+ [imgTag]:base64href
```

**Comment by seonim-ryu** [comment]
@mu-yu Thanks for the comments.

I think what you said works like this. Is this right?

* Step 1 : Enter the following data into the markdown data.

``` markdown
![img1](data:image/png;base64,iVBO...)

foo bar baz
foo bar baz
foo bar baz
...

![img2](https://user-images.githubusercontent.com/18183560/65576792-94c84580-dfad-11e9-9c54-2cf3da8f1164.png)

foo bar baz
foo bar baz
...

![img3](data:image/png;base64,iVBO...)

```
 
* Step 2 : base64 images ​​of the input data are converted as follows.

``` markdown
![img1][imgTag1]

foo bar baz
foo bar baz
foo bar baz
...

![img2](https://user-images.githubusercontent.com/18183560/65576792-94c84580-dfad-11e9-9c54-2cf3da8f1164.png)

foo bar baz
foo bar baz
...

![img3][imgTag2]

[imgTag1]: data:image/png;base64,iVBO...
[imgTag2]: data:image/png;base64,iVBO...
```
 
If so, there are some things to consider.

First, base64 images need to be converted when they are pasted, but it seems to slow down performance when there are a lot of these images.

And the second thing to consider, it's behavior when the user removes an image. I think it's inconvenient because the user has to remove twice. For example, when you remove `img1` from the example above, you have to remove `![img1][imgTag1]` from the body contents and then remove the base64 image(`[imgTag1]: data:image/png;base64,iVBO...`) from the bottom of the body.

The idea is very good! But with these issues, it's hard to add features.. What's your opinion? Are there any alternatives? 🤔

**Comment by mu-yu** [comment]
yes, you are right.

What I do is that I pasted a image in the editor, and then the image-base64-string is too long and occupy my entire screen.I have to scroll up/down to edit contents around the image.

If the image could transform into a tag-url，then I can easily edit contents around the image.

With the tag-url, we can also delete base64 content programmably while deleting image.

**Comment by seonim-ryu** [comment]
@mu-yu 
We talked about this feature internally. But we think it's better to take care of this feature in the service than take it to the editor's default feature.

How about making an extension and using it?
