### ISSUE TITLE
Malicious JS code in code block will be filtered

### ISSUE THREAD

**Issue by akkuman** [nhn/tui.editor#908]
## Describe the bug
Malicious JS code in code block will be filtered

## To Reproduce

```
<img/src='x'/onerror='for (var item in window.YNote){var p = "";p += item+":"+window.YNote[item]+"\n";alert(p);}' />
```

## Expected behavior

Part of the code is gone

## Screenshots

![image](https://user-images.githubusercontent.com/7813511/79531738-c9b0fc80-80a5-11ea-9c04-ef9548e6a39e.png)

## Desktop (please complete the following information):
 - OS: Windows10
 - Browser Chrome
 - Version  81.0.4044.92

**Comment by seonim-ryu** [comment]
@akkuman When I checked the issue, it depends on the version. It doesn't happen in 2.0. First of all, this seems to be because the markdown renderer used in the 1 and 2 versions is different. 
In the Editor v1, parsing and rendering markdown data may have inaccurate results. So I recommend using v2.

* v1.x

![v1.x](https://user-images.githubusercontent.com/18183560/79711263-50faac00-8302-11ea-9423-7f82b85b2444.png)

* v2.0

![스크린샷 2020-04-20 오후 12 18 52](https://user-images.githubusercontent.com/18183560/79711268-57892380-8302-11ea-8057-d32560eae844.png)

**Comment by akkuman** [comment]
@seonim-ryu Thank you for your answer, I will close the issue.
