### ISSUE TITLE
How to replace with regexp when in preview and viewer?

### ISSUE THREAD

**Issue by eshengsky** [nhn/tui.editor#977]
## Summary
How to replace with regexp when in preview and viewer?

## Screenshots
none

## Version
the latest v2+ version

## Additional context
I'm trying to write a plugin to this awesome editor in my project, that will insert emoji icon, with following steps:
1. User click a button, and select a emoji to insert it into editor(such as :cry :, :smile :)
2. In preview panel, or in viewer component, replace these special code (/:\w+:/) to HTML (< img src="xxx" / >)
Now the 1st step I've done, but I don't konw how to do the 2nd step.
Any help? Thanks!

**Comment by seonim-ryu** [comment]
@eshengsky If emoji text (e.g. `:cry :`, `:smile :)`) is entered in the markdown editor and you want to handle the purpose of simply converting the value when rendered in the preview area, the internally used event (`convertorAfterMarkdownToHtmlConverted`) can be used through the `hooks` option. However, I don't recommend this because it is not a normal method.

I think the best way to handle this is with `customHTMLRenderer`. Would you like to review the link below and see if it will work?

> https://github.com/nhn/tui.editor/blob/master/apps/editor/docs/custom-html-renderer.md

**Comment by eshengsky** [comment]
I use `convertorAfterMarkdownToHtmlConverted` event to resolve it. Thanks!
